channels:
  - defaults
  - conda-forge
dependencies:
  # renovate: datasource=conda depName=main/python
  - python=3.12.6
  # renovate: datasource=conda depName=main/pip
  - pip=24.2
  # renovate: datasource=conda depName=main/pydantic
  - pydantic=2.8.2
  # renovate: datasource=conda depName=main/mypy
  - mypy
  # renovate: datasource=conda depName=main/pytest
  - pytest=7.4.4
  - pip:
      # renovate: datasource=pypi
      - "-e .[dev]"
